### ISSUE TITLE
setAuthId set $this->authId but auth (without ID) is used in Class

### ISSUE THREAD

**Issue by Newan** [confirm/PhpZabbixApi#26]
when i try to loggin with my sessionkey (autId) i have to put the string in the auth paramter.

`    public function setAuthId($authId)
    {
        $this->auth = $authId;
        return $this;
    }
`
Currently, my opinion, is set to the wrong paramter `$this->authId = $authId;`

**Comment by domibarton** [comment]
Hi there

Sorry I don't understand what's your exact problem. You can either login with the username and password OR the authID.

You can use the [constructor](https://github.com/confirm/PhpZabbixApi/blob/master/templates/abstract.tpl.php#L148) or the [setAuthId() method](https://github.com/confirm/PhpZabbixApi/blob/master/templates/abstract.tpl.php#L197).

Cheers
Domi

**Comment by Newan** [comment]
i woud to login with the session key from the cookie or as response from the normal login with username an password. It is save as $auth  parameter in the claas

**Comment by domibarton** [comment]
Yes you're right, I didn't use the `$authId` in the class (I think it should be `$this->auth` instead of `$this->authId`). I'll fix it asap!

Thanks!

**Comment by domibarton** [comment]
It's fixed with commit 1941d4c615e6cc6df35ebcd492eeeeadbddbe227, respective a0868bb2464de3d00de42fc14be6ec40a4c61500 and 820f635e0c3e4dee418145ad0ba9ef506747757e.  
Use the [2.2 branch](https://github.com/confirm/PhpZabbixApi/tree/2.2) or [2.4 branch](https://github.com/confirm/PhpZabbixApi/tree/2.4) or the [2.2.5 tag](https://github.com/confirm/PhpZabbixApi/releases/tag/v2.2.5) or [2.4.5 tag](https://github.com/confirm/PhpZabbixApi/releases/tag/v2.4.5) for testing.

Cheers
Domi

**Comment by Newan** [comment]
thanks
