### ISSUE TITLE
Method trendGet() not found at v2.2.2

### ISSUE THREAD

**Issue by kiserbd** [confirm/PhpZabbixApi#35]
@domibarton Getting this Error: Call to undefined method ZabbixApi\ZabbixApi::trendGet() to get the history of day interval graph. Am i doing anything wrong here or its a bug? Thanks in advance.

**Comment by oksim14** [comment]
Any progress with this issue? Thanks

**Comment by domibarton** [comment]
Hi guys

As mentioned in #28, I'm no longer using PHP or Zabbix and therefor I think I can't help you guys right now. 

If I've to guess, then I'd say Zabbix probably updated their version and the library wasn't rebuilt since then. Have you tried to build the library via `php build.php` with the latest Zabbix version?

Cheers
Domi
